import numpy as np
from cmath import inf
import matplotlib.pyplot as plt
from opendrift.models.oceandrift import OceanDrift
from opendrift.readers import reader_netCDF_CF_generic
import xarray as xr
import os


def FTLE(DataArray, outfile=None, separation = None, duration=None, model=True, model_file = '/lustre/storeB/project/fou/hi/barents_eps/eps/barents_mean_20231018T06Z.nc', proj4='+proj=lcc +lat_0=77.5 +lon_0=-25 +lat_1=77.5 +lat_2=77.5 +no_defs +R=6.371e+06', RLCS = False, show=False):
    """
        Computes LCSs using the FTLE approach using the file from ParticleAdvector.py
        The function is tailored for attracting hyperbolic LCSs. If repelling LCSs are of interest, the resulting array needs to be reversed, i.e. RLCS[::-1, ::-1].
    Args:
        DataArray  [xr.DataArray]    :   Name of file which contains intial and final positions of particles. Generated by ParticleAdvector.py
        outfile    [str]             :   Name of file where LCSs are saved to.
        DG         [bool]            :   Set to "True" if LCSs are to be generated for the Double-Gyre system. 
    Retunts:  
        outfile.nc [str]             :   Name of file where LCSs are saved to. 
    """
    if separation is not None:
        sep = separation
    else:
        sep = DataArray.separation.values
    if duration is not None:
        dur = duration
    else:
        dur = DataArray.duration.values

    x0 = np.array(DataArray.lon)
    y0 = np.array(DataArray.lat)

    nx, ny = x0.shape[0], x0.shape[1]
    x1 = np.reshape(np.array(DataArray.nlon), (nx, ny))
    y1 = np.reshape(np.array(DataArray.nlat), (nx, ny))

    ftle = np.zeros([nx,ny])
    for i in range(1,nx-1):
        for j in range(1,ny-1):
            
            F = np.zeros([2,2])
            F[0,0] = (x1[i+1, j]-x1[i-1, j])/(2*sep)
            F[0,1] = (x1[i, j+1]-x1[i, j-1])/(2*sep)
            F[1,0] = (y1[i+1, j]-y1[i-1, j])/(2*sep)
            F[1,1] = (y1[i, j+1]-y1[i, j-1])/(2*sep)
            
            C = np.dot(np.transpose(F), F)

            try:
                vals, vecs = np.linalg.eig(C)
            except:
                vals = 0
            np.seterr(divide = 'ignore')
            ftle[i,j] = np.log(np.sqrt(np.max(vals)))/dur
    ftle[ftle==-inf]=np.nan
        
    if model is True:
        # It's important to have the correct file here for the projection
        r = reader_netCDF_CF_generic.Reader(model_file, proj4=proj4)
        x0, y0 = r.xy2lonlat(x0, y0)

    if RLCS is False:
        ftle = ftle[::-1,::-1]
        LCS = xr.Dataset(coords = dict(lon=(['x', 'y'], x0), lat=(['x','y'], y0)),
                    data_vars = dict(ALCS=(['x', 'y'], ftle)))
    elif RLCS is True:
        LCS = xr.Dataset(coords = dict(lon=(['x', 'y'], x0), lat=(['x','y'], y0)),
                    data_vars = dict(RLCS=(['x', 'y'], ftle)))
        
    if outfile is not None:
        LCS.to_netcdf(f'{outfile}.nc')

    if show is True:
        rlcs = np.array(LCS.ALCS)
        from opendrift.readers import reader_double_gyre
        double_gyre = reader_double_gyre.Reader(epsilon=0.25, omega=0.582, A=0.1)
        plt.figure(dpi=300)
        plt.pcolormesh(LCS.lon, LCS.lat, rlcs, cmap='Reds')
        plt.colorbar()
        colors = ['Blue', 'Black']
        labels = ['Start', 'End']
        for i in [0,-1]:
            pos = xr.open_dataset('shear_particles.nc').isel(time=i)
            posx, posy = double_gyre.proj(pos.lon, pos.lat)
            plt.scatter(posx, posy, s = 1, color=colors[i], label=labels[i])
        plt.legend()
        plt.show()

    return LCS

if __name__ == '__main__':
    ftle = FTLE(xr.open_dataset('double_gyre_particles.nc'), model=False, outfile='dg_test')
    plt.pcolormesh(ftle.lon, ftle.lat, ftle.ALCS)
    plt.show()


    